<?php

use Illuminate\Database\Seeder;
use App\Models\SkillsCategory;
use App\Models\Skill;

class SkillsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            "Methodes" => [
                "Agile",
                "ALM Aipplication Lifecycle Management",
                "Analyse de l'activite",
                "Archimate",
                "Atelier de co conception",
                "Conception centree utilisateur",
                "C'ycle en V",
                "Cycle en Y",
                "Design Patterns",
                "Design Thinking",
                "DevOps",
                "EBIOS",
                "Extreme Programming (XP)",
                "GPP",
                "GPP NG Agile",
                "GPP NG Waterfall",
                "Ishikawa",
                "ISOM",
                "Kanban",
                "Lean",
                "Machines Abstraites",
                "MDA",
                "Merise",
                "OMT Object Modeling Technique",
                "OWASP",
                "RUP",
                "SADT",
                "SAM Sofhware Asset Management",
                "Scrum",
                "SDM/S",
                "Six Sigma",
                "TCO   Total Cost of Ownership",
                "TDD (Test Driven Dev)",
                "Test utilisateur",
                "TOGAF",
                "UML",
                "Unified Process",
            ],
            "Outils et produits" => [
                "Outils & Produits",
                "ETL",
                "Gestion de configuration",
                "IDE",
                "ITSM",
                "Modelisation",
                "Pack Office",
                "Testing",
                "Cast",
                "CheckStyle",
                "Cobertura",
                "Cucumber",
                "FindBugs",
                "Fortify",
                "Hiptest",
                "HP ALM Quality Center",
                "instrument",
                "Jmeter",
                "HP LoadRunner",
                "JProfiler",
                "JUnit",
                "Lime",
                "Mercury",
                "MochaJS",
                "OpenSTA",
                "PHPUnit",
                "Selenium",
                "Sonar",
                "SQUASH TM, TA",
                "TestLink",
                "Unified Functional Testing (UFT)",
                "XTC (eXtensive Testing)",

            ],
            "ETL" => [
                "AB Initio",
                "Apache Camel",
                "BizTalk",
                "Data Transformation Services (DTS)",
                "Datastage",
                "Genio",
                "Informatica",
                "Oracle Sunopsis",
                "OWB   Oracle Warehouse Builder",
                "Talend",
            ],
            "Gestion de configuration" => [
                "Ansible",
                "ChangeMan",
                "ClearCase",
                "Clearquest",
                "CVS",
                "Endevor",
                "Git",
                "Gogs(Git)",
                "HP uCMDB",
                "iTop",
                "Puppet",
                "PVCS Dimensions",
                "RUDDER",
                "Saltstack",
                "StarTeam",
                "Subversion (SVN)",
                "Team Foundation Server (TFS)",
                "TeamStudio",
                "XCAT",
            ],
            "IDE" => [
                "Ant",
                "Brackets",
                "Delphi",
                "Emacs",
                "Flexera InstallShield",
                "IntelliJ",
                "JBuilder",
                "LabVIEW",
                "Maven",
                "NetBeans",
                "PhpStorm",
                "Progress OpenEdge",
                "PyCharm",
                "Qt Creator",
                "SQL Developer",
                "Sublime Text",
                "Visual Studio",
                "Visual Studio Code",
                "WEBDEV",
                "Webstorm",
                "WINDEV",
                "WSAD",
                "XCode",
            ],
            "ITSM" => [
               "CA Service Desk manager",
               "Easyvista",
               "Glpi",
               "HEAT (Frontrange)",
               "HP Service manager",
               "Remedy",
               "ServiceNow",
            ],
            "Modelisation" => [
                "3Ds max",
                "ARCHI",
                "ArgoUML",
                "Cinema4D",
                "Kibana",
                "Mega",
                "Oracle designer",
                "PowerAMC",
                "Rational Rose",
                "Rational Software Architect",
                "StarUML",
                "Win Design",
                "yEd Graph Editor",
            ],
            "Pack Office" => [
                "Microsoft Access",
                "Microsoft Excel",
                "Microsoft OneNote",
                "Microsoft Outlook",
                "Microsoft PowerPoini",
                "Microsoft Publisher",
                "Microsoft Visio",
                "Microsoft Word",
            ],
            "Testing" => [
                "Cast",
                "CheckStyle",
                "Cobermra",
                "Cucumber",
                "FindBugs",
                "Fortify",
                "Hiptest",
                "HP ALM Quality Center",
                "HP LoadRunner",
                "Instrument",
                "Jmeter",
                "JProfiler",
                "JUnit",
                "Lime",
                "Mercury",
                "MochaJS",
                "OpenSTA",
                "PHPUnit",
                "Selenium",
                "Sonar",
                "SQUASH TM, TA",
                "TestLink",
                "Unified Functional Testing (UFT)",
                "XTC(eXtensh e Testing)",
            ],
            "Produits" => [
                "Adobe analytics",
                "Adobe Campaign",
                "Adobe Dreamweaver",
                "Adobe Illustrator",
                "Adobe Indesign",
                "Adobe Photoshop",
                "Adobe XD",
                "Alfresco",
                "AMASIS",
                "Argoline",
                "Arisem",
                "AutoCad",
                "Balsamiq",
                "Beyond Compare",
                "Birt",
                "BSCS",
                "Calliope",
                "Canopsis",
                "CashSolve",
                "Catia",
                "ChaRM (Change Request Management)",
                "CICS",
                "Ciel",
                "Clarity",
                "Copernic",
                "Cornerstone",
                "Crystal Reports",
                "Cumulocity",
                "DBIII",
                "DbVisualizer",
                "Documentum",
                "DOORS",
                "Dovecot",
                "Drools",
                "Drupal",
                "E GEN",
                "Easytrieve",
                "ElasticSearch",
                "ENOVIA",
                "Enterprise Architect",
                "Entity Framework (part of .NET Framework)",
                "Everest",
                "EverSuite",
                "FileMaker Pro",
                "FileZila",
                "Flexnet",
                "FusionCharts",
                "GEMO",
                "Genesys",
                "Genesys ESen.ices et IWD",
                "Genesys Framework",
                "Genesys Sip Server",
                "Gimp (GNU Image Manipulation Program)",
                "Google Analytics",
                "HR access",
                "IAM (CA)",
                "IBM Rational Team Concert (RTC)",
                "IBM WebSphere ILOG JRules",
                "IceScnim",
                "IMS information Management system",
                "InfoEngine",
                "Inkscape",
                "IReport",
                "Joomla",
                "Jupyter",
                "Leasebase",
                "Livelink",
                "Logstash",
                "MagicDraw",
                "Maximo",
                "MediaWiki",
                "Microstrategy",
                "Migration manager for Active Directory",
                "MobaXtern",
                "MS Project",
                "MSBI",
                "MySQL Workbench",
                "NetCDF",
                "Nginx(serveur Web)",
                "Nuxeo",
                "Office 365",
                "OOZ",
                "OPX2",
                "Oracle Application Express   APEX",
                "Oracle Forms Reports",
                "OWB Open Workbench",
                "Pack Office",
                "PHP MyAdmin",
                "Pipeline Pilot",
                "Planisware PPM",
                "Procreate",
                "Putty",
                "PVCS Tracker",
                "Quest Active Roles Server",
                "Quest Notes Migrator for SharePoint (NMSP)",
                "Rational Change",
                "Rational Synergie",
                "RDz Rational Developer for z systems",
                "Redmine",
                "Reqtify",
                "ScketchBook",
                "Serveur WMS   Web Map Service",
                "Skype for Business",
                "SoapUI",
                "SolarWinds NCM",
                "SQL Loader",
                "SQRIBE",
                "Squirrel",
                "Ssh Secure Shell",
                "StreamWeaver",
                "SWIFT Alliance",
                "TDS",
                "TeamCenter",
                "Terraform",
                "TIBCO Rendezvous",
                "TOAD",
                "TSO",
                "Tufin",
                "Twig(PHP template engine)",
                "Valgrind",
                "Genesys Voice Platform",
                "Virtual Box",
                "Windchill",
                "WinScp",
                "Wordpress",
                "WS2 API manager",
            ],
            "Qualite & Certification" => [
                "Certification Agile PM",
                "Certification Amazon Web Services (AWS)",
                "Certification Azure",
                "Certification CAPM",
                "Certification CEH",
                "Certification CENTREON/NAGIOS",
                "Certification CHFI",
                "Certification CISA",
                "Certification CISCO",
                "Certification CISM",
                "Certification CISSP",
                "Certification Citrix",
                "Certification Coach Agile",
                "Certification CoBIT",
                "Certification DevOps",
                "Certification e SCM",
                "Certification EMC2",
                "Certification EN 9100",
                "Certification F5 Networks",
                "Certification Genesys",
                "Certification HITACHI",
                "Certification HP",
                "Certification IBM",
                "Certification IREB",
                "Certification ISO 27001 :securite",
                "Certification ISO 27002 : securite",
                "Certification ISO 27005 : securite",
                "Certification ISTQB",
                "Certification ITIL",
                "Certification J2EE",
                "Certification Leading SAFe",
                "Certification Lean",
                "Certification LPIC",
                "Certification Microsoft",
                "Certification Microsoft MCSA Office 365",
                "Certification Microsoft MCSE Cloud Plaftorm",
                "Certification NetApp",
                "Certification Nettasq",
                "Certification NUTANIX",
                "Certification Oracle",
                "Certification PgMP",
                "Certification PMP",
                "Certification Prince2",
                "Certification REQB",
                "Certification Scrum Master",
                "Certification Six Sigma",
                "Certification Stormshield",
                "Certification TOGAF",
                "Certification VMware",
                "CMMI",
                "DO 178",
                "EX200   RedHat Certified System Administrator",
                "EX300  RedHat Certified Engineer",
                "ISO 20000:centre de service， production inf",
                "ISO 9001",
                "ISO 9241 210   Ergonomie de 1'IHM",
                "SWGR",
            ],
            "Technique" => [
                "Annuaire",
                "Base de donnSes",
                "BI",
                "Big Data",
                "Cloud",
                "Collaboratif",
                "Data Science",
                "Deploiement",
                "EAI",
                "Eclipse",
                "ERP",
                "HPC (High Performance Computing)",
                "Integration continue",
                "JEE (J2EE)",
                "JSE",
                "Langages",
                "Messagerie",
                "Mobilite",
                "Orchestration",
                "Ordonnancement",
                "Postes de travail",
                "Reseaux (LAN&WAN)",
                "Sauvegarde & Stockage",
                "Serveurs",
                "Serveurs Application",
                "Supervision & Metrologie",
                "Systeme",
                "Securite",
                "Telephonie",
                "Virtualisation",
                "Web",
                "Workflow ",
                "Acceleo",
                "Apache Solr   Apache Lucene",
                "CoAP (Constrained Application Protocol)",
                "HDF 5 (format de fichier)",
                "IBM General Parallel File System (GPFS)",
                "Oracle Primavera",
                "Pacemaker",
                "Pentest",
                "Redis (REmote Dictionary Server)",
                "Silverlight",
                "Winform",
            ],
            "Annuaire" => [
                "Active Directory",
                "Centrify",
                "EDirectory",
                "Group Policy Object (GPO)",
                "JXplorer",
                "LDAP",
                "Meta Annuaire",
                "NDS Novell Directory Services",
                "Open LDAP",
            ],
            "Base de données" => [
                "Adabas",
                "Clio",
                "Dataguard",
                "DB2",
                "DBase IV",
                "DL1",
                "HSQLDB",
                "IDMS Integrated Database Management",
                "System",
                "IDS2",
                "InfluxDB",
                "Informix",
                "Ingres",
                "Liquibase",
                "MariaDB",
                "MongoDB",
                "MySQL",
                "Neo4J",
                "NoSql",
                "Oracle",
                "Oracle Exadata",
                "Oracle golden gate",
                "Oracle RAC (Real Application Clusters)",
                "PI System______",
                "PostgreSQL",
                "PouchDB",
                "SQLite",
                "SQLServer",
                "Sybase",
                "Sybase Replication",
                "SymmetricDS",
                "Teradata",
            ],
            "BI" => [
                "BO Designer",
                "BOXI",
                "Business Objects (BO)",
                "Cognos",
                "Hyperion",
                "Jasper Report",
                "Microsoft Power BI",
                "Open Source",
                "Oracle Business Intelligence Discover",
                "Pentaho",
                "QlikView",
                "Report Services (SSRS Microsoft)",
                "SAP BW",
                "SAP BI4",
                "SAS",
                "TableauSofhvare",
                "Weblntelligence",
            ],
            "Big Data" => [
                "Apache Drill",
                "Apache Kafka",
                "Apache NiFi",
                "Apache Pig",
                "Apache Spark",
                "BerkleyDB",
                "Cassandra",
                "Cloudera",
                "Couchbase",
                "CouchDB",
                "GridGain",
                "Hadoop",
                "HBase",
                "Hive",
                "Hortonworks",
                "HPCC",
                "Machine learning",
                "MapR",
                "MapReduce",
                "OrientDB",
                "Riak",
                "Sinequa",
                "Storm",
            ],
            "Cloud" => [
                "AWS (Amazon)",
                "Azure (Microsoft)",
                "GCP Google Cloud Platform",
                "OCB (Orange)",
                "OVH",
            ],
            "Collaboratif" => [
                "BEA Portal",
                "Confluence",
                "e Room",
                "Jahia",
                "Liferay",
                "Lotus Domino",
                "SharePoint",
            ],
            "Data Science" => [
                "Analyses factorielles",
                "Data Science",
                "Datamining",
                "IBM Cognos",
                "KNIME",
                "Mahout",
                "MATLAB",
                "OpenCV",
                "Oracle Data Miner",
                "Probabilites",
                "Qlik",
                "R Studio",
                "RapidMiner",
                "Regressions",
                "Scilab",
                "Series Temporelles",
                "STATA",
                "Statistiques",
                "Statistiques avancées",
                "Statistiques descriptives",
                "Statistiques inférentielles",
                "TIBCO Spotfire",
                "Time Series",
                "Weka",
            ],
            "Deploiement" => [
                "IT Client manager CA",
                "LanDesk",
                "MDT Microsoft Deployment Toolkit",
                "Satellite",
                "Symantec Ghost solution Suite",
                "ZENWorks (Novell)",
            ],
            "EAI" => [
                "BEA",
                "MQ Series",
                "TFT (Gestion flux mainframe)",
                "TIBCO",
                "WebMethods",
            ],
            "Eclipse" => [
                "Eclipse",
                "Eclipse GEF (Graphical Editing Framework)",
                "Eclipse GMF Graphical Modeling Framework）",
                "Eclipse RCP",
                "Eclipse UML",
            ],
            "ERP" => [
                "GBS",
                "Generix",
                "Microsoft Dynamics",
                "Microsoft Dynamics AX",
                "Microsoft Dynamics CRM",
                "Oracle applications",
                "Peoplesoft",
                "Qualiac",
                "SAP",
                "Siebel",
            ],
            "HPC (High Performance Computing)" => [
                "BullX",
                "GPF5",
                "IBMLSF",
                "Infiniband",
                "LUSTRE",
                "SGE",
                "SGI",
            ],
            "Integration continue" => [
                "Archiva",
                "Bamboo",
                "Bitbucket",
                "Bugzilla",
                "GitLab",
                "HockeyApp",
                "Hudson",
                "Integration Continue",
                "Jenkins",
                "Jira",
                "Mantis",
                "MSBuild Microsoft Build Engine",
                "Nexus",
                "Polarion",
            ],
            "JEE" => [
                "JEE (J2EE)",
                "Apache CXF",
                "Apache POI Java API for Microsoft Documents",
                "CDI",
                "Content Repository API for Java (JCR)",
                "EhCache",
                "EJB",
                "Interceptors",
                "JAF",
                "Java Serv let",
                "JavaMail",
                "JAX RPC",
                "JAX RS (Rest)",
                "JAX WS",
                "JAXB",
                "JAXM",
                "JAXP",
                "JAXR",
                "JCA Java Connector Architecture",
                "JEE",
                "Jersey",
                "JFC",
                "JMS",
                "JPA",
                "JSF",
                "JSON",
                "JSON P",
                "JSP",
                "JSTL",
                "JTA",
                "Log4J",
                "Logback",
                "Odata",
                "Play",
                "Quartz (Job scheduling)",
                "Slf4J",
                "SOAP",
                "Spring Boot",
                "StAX",
                "Web Socket",
            ],
            "JSE" => [
                "Advanced Message Queuing Protocol(AMQP)",
                "Applet",
                "AWT",
                "Java 3D",
                "Java Advanced Imaging",
                "Java Media Framework",
                "Java OpenGL JOGL",
                "Java Security",
                "Java Sound",
                "Java Web Start",
                "Java2D",
                "JavaFX",
                "JCA  Java Crypto API",
                "JDBC",
                "JfreeChart",
                "JMX",
                "JNDI",
                "JNI",
                "JSE",
                "RMI",
                "Swing",
            ],
            "Languages" => [
                "CSS",
                "CSS3",
                "Less",
                "PostCSS",
                "CSSnext",
                "Sass",
                "Abal",
                "ABAP",
                "Ada",
                "AntLR",
                "ASP",
                "ASP.Net",
                "MVC",
                "Assembleur",
                "Bash",
                "Batch Scripting",
                "C",
                "C#",
                "C++",
                "CLIPPER",
                "Cobol",
                "ColdFusion",
                "Cshell",
                "dotNet",
                "DTD",
                "Flash",
                "Flex",
                "Fortran",
                "Groovy",
                "Haskell",
                "HTML",
                "HTML 5",
                "IDL (Interactive Data Language)",
                "IQS commandes et requetage",
                "Java",
                "Javascript (JS)",
                "JCL",
                "jQuery",
                "Python",
                "Komshell",
                "Langage R",
                "LaTeX",
                "LINQ   Language Integrated Query",
                "Lisp",
                "Lotus Script",
                "Maple",
                "NatStar",
                "Natural Language",
                "NSDK",
                "Objective C",
                "PacBase",
                "Pandas",
                "Pascal",
                "Perl",
                "PHP",
                "PL SQL",
                "PL7",
                "PowerBuilder",
                "Powershell",
                "Prism",
                "Pro*C",
                "Pro*Cobol",
                "PV Wave (RogueWave)",
                "PyQT",
                "Python",
                "Qt",
                "REXX (Restructured Extended Executor)",
                "RPG  Report Program Generator",
                "Ruby",
                "Scikit leam",
                "SGML",
                "Shell",
                "Socrate/Clio",
                "SPARQL",
                "SQL",
                "Standard ML (SML)",
                "React",
                "Swift",
                "TCLTK",
                "Transac SQL",
                "TypeScript",
                "VBA  Visual Basic for Applications",
                "VBScript",
                "Visual Basic",
                "Visual Basic .Net",
                "WinRT",
                "X",
                "XAML",
                "Xquery",
                "XSL",
                "XSL FO",
                "XSLT",
                "Xtext DSL",
                "Yaml",
                "React Native",
                "Node.JS",
                "Vue.JS",
            ],
            "Messagerie" => [
                "Ejabberd",
                "Exchange",
                "Groupwise",
                "Lotus Notes",
                "Lotus Web",
                "Postfix",
                "Zimbra",
            ],
            "Mobile" => [
                "AirWatch",
                "Bluetooth",
                "Google Maps",
                "Ionic",
                "iOSUI",
                "J2ME",
                "PhoneGap",
                "Plan",
                "RestKit",
                "Windows Store",
                "WPF",
                "Xamarin",
                "ReactNative",
            ],
            "Orchestration" => [
                "HP Operations Orchestration",
                "Microsoft Orchestrator",
                "Sen iceNow, module Orchestration",
                "VRA   VMware vRealize Automation",
                "VRO VMware vRealize Orchestrator",
            ],
            "Ordonnancement" => [
                "SUniverse",
                "Automator",
                "Beta 92 48",
                "CA Autosys",
                "CA 7",
                "CFT Cross File Transfert",
                "Control M",
                "Cortex",
                "MQSeries",
                "OneAutomation (AUTOMIC/CA)",
                "OPC Ordonnancement Pilotage Coordination",
                "TSM",
                "TSO (Time Sharing Option)",
                "TWS   Tivoli Workload Scheduler",
                "Vega",
                "Vtom",
            ],
            "Postes de travail" => [
                "Altiris",
                "OCS Inventory",
                "OpenOffice",
                "Poste de travail Linux",
                "Poste de travail Windows",
                "SCCM",
            ],
            "Reseaux (LAN&WAN)" => [
                "3Com",
                "A429",
                "AFDX (Avionics FuU DupleX)",
                "ATM Asynchronous Transfer Mode",
                "Avaya",
                "Brocade",
                "Cacti",
                "Cisco",
                "Ethernet",
                "Fibre Channel",
                "Firewall",
                "FTP File Transfer Protocol",
                "Icsci",
                "IP  Internet Protocol",
                "LAN",
                "Netscaler",
                "Nortel",
                "Protocole HTTP",
                "Protocole IP V4",
                "Protocole IP V6",
                "Protocole MP BGP",
                "Protocole MPLS",
                "Protocole MSDP",
                "Protocole Netflow",
                "Protocole OAM",
                "Protocole OSPF",
                "Protocole PIM",
                "Switch Ethernet",
                "TCP/IP",
                "WAN",
                "Wifi",
                "X25",
            ],
            "Sauvegarde & Stockage" => [
                "ArcServe",
                "Atlantis Computing",
                "Avamar",
                "BackUp Exe",
                "Ceph",
                "Cristie",
                "Datacore",
                "Dataprotector",
                "DELL Storage",
                "DPM (Data Protection Manager)",
                "DRBD",
                "EMC2 Clarion",
                "EMC2 DataDomain",
                "EMC2 DMX",
                "EMC2 VUAX",
                "EMC2 VNX",
                "Exabuilder",
                "HDS (Hitachi Data System)",
                "HP EVA",
                "HPE 3Par",
                "IBM Storage Hybrid",
                "IBM Stonvize",
                "NetApp",
                "NetBackup",
                "NetWorker",
                "Nutanix",
                "Oracle HSM",
                "Oracle Tuxedo",
                "Overland Storage",
                "OwnCloud",
                "Rman",
                "Rubrik",
                "SAN",
                "SAN Brocade",
                "SAN/NAS",
                "SIMPLI\1TY",
                "StorageTek",
                "SUN Storage",
                "Tina",
                "Veeambackup",
                "Vplex",
                "VSAM (Virtual Storage Access Method)",
            ],
            "Serveurs" => [
                "Bull",
                "DELL",
                "HP",
                "IBM Flex System",
                "IBM LPM (Live Partition Mobility)",
                "IBM Power",
                "LinuxHA",
                "Microsoft serveur",
                "Mondrian (Serv eur OLAP, suite Pentaho)",
                "PSeries IBM",
                "Radius",
                "SIOS Lifekeeper",
                "Solaris",
                "SUN server",
            ],
            "Serveurs Application" => [
                "Active Directory Certificate Serv ices",
                "Apache",
                "Apache Karaf",
                "Apache Wookie",
                "ARIS",
                "BEA Weblogic",
                "GlassFish",
                "IBM Websphere",
                "IIS",
                "JBoss",
                "JOnAS",
                "Tomcat",
                "WildFly",
            ],
            "Supervision & Metrologie" => [
                "BMC Enterprise Manager",
                "BPM   Business Process Management",
                "Business Bridge",
                "CA Unified Infra Management",
                "Centreon",
                "Ciscoworks LAN Management",
                "DYNATRACE",
                "EON (Eyes Of Network)",
                "Eyes Of Network",
                "HP Openview HP BTO",
                "InfoVista",
                "IP Label",
                "Nagios",
                "Newtest",
                "Omnivision",
                "Patrol",
                "RTC",
                "SCOM (System Center Operations Manager)",
                "Sentinel",
                "Shinken",
                "SNMP Simple Network Management",
                "Protocol",
                "Sysload",
                "Tivoli",
                "Zabbix",
            ],
            "Systeme" => [
                "AIX",
                "AIX HA CMP",
                "Android",
                "Arduino",
                "AS 400 (OS 400)",
                "CentOs",
                "Debian",
                "DPS",
                "Fedora",
                "FreeBSD",
                "Freenas",
                "GCOS",
                "HP Mc ServiceGuard",
                "HP UX",
                "HP9000",
                "IBMES9000",
                "IBMVM/ESA",
                "iOS",
                "iSeries",
                "Linux",
                "MAC",
                "MVS",
                "Nas4Free",
                "NOS/VE",
                "Novell Netware",
                "OSX",
                "Redhat",
                "Suse",
                "Unix",
                "VAX/VMS",
                "Windows",
                "Windows Phone",
                "Windows server",
                "Z OS",
            ],
            "Securite" => [
                "Alteon",
                "Barracuda",
                "Bluecoat",
                "Checkpoint",
                "Cisco ASA",
                "DNS/DHCP",
                "eTrust",
                "F5 securite load balancer",
                "Fortinet",
                "Hacking",
                "Infoblox",
                "Juniper",
                "Kaspersky",
                "McAfee",
                "Nessus",
                "Netasq Stormshield",
                "Netscreen",
                "Oauth",
                "OpenS SL",
                "PKI",
                "Riverbed",
                "SonicWall",
                "Sophos",
                "SPLUNK",
                "SSL.TLS",
                "SSO (Single sign one)",
                "Stonesoft",
                "Symantec",
                "Symantec Endpoint Protection",
                "VPN",
                "Wallix",
                "WSUS",
            ],
            "Telephonie" => [
                "Alcatel",
                "Cisco Unified Communications ManagerCUCM",
                "Datalink",
                "PABX",
                "TOIP",
                "Trixbox",
                "VOIP",
                "Xivo",
            ],
            "Virtualisation" => [
                "AIX Live Partition Mobility   LPM",
                "Citrix",
                "Docker",
                "Docker xen",
                "ESX",
                "ESXi",
                "Hyper V",
                "IBMHMC",
                "IBM PowerVM",
                "IVM Integrated Virtualization Manager (IBM)",
                "Kubemetes",
                "KVM",
                "LXC Linux Containers",
                "NSX",
                "OpenNebula",
                "OpenStack",
                "Oracle VM",
                "Proxmox",
                "Redhat Openshift Container Platform",
                "RHEV",
                "SCVMM",
                "Solaris Virtualisation (Container)",
                "SRM   Site Recovery Manager",
                "vCenter",
                "VCloud",
                "VConnect (Cloud Assert)",
                "Virtual I/O",
                "Virtual PC",
                "VirtualBox",
                "VMware",
                "VMware View",
                "vsphere",
                "XenApp",
                "XenDesktop",
                "XenServer",
            ],
            "Web" => [
                "ActiveX",
                "Ajax",
                "Angular",
                "AngularJS",
                "AOP",
                "Bootstrap",
                "Bower",
                "CakePHP",
                "Codeigniter",
                "Corba",
                "Cordova",
                "CoreData",
                "D3.js Data Driven Documents",
                "EJS Embedded Javascript templates",
                "EmberJS",
                "ES2016 (EcmaScript 6)",
                "ExtJS",
                "Flying Saucer (XHTML Tenderer)",
                "Grails Framework (Groovy)",
                "Grunt",
                "Gulp",
                "GWT",
                "Hibernate",
                "ICEfaces JSF",
                "JDO",
                "JS View",
                "KeyLines",
                "Laravel",
                "Leaflet (JS Library)",
                "MapGuide",
                "Materialize",
                "Npm Node Package Manager",
                "OpenAPI",
                "Openlayers",
                "OSGi",
                "PrimeFaces",
                "ReactJS",
                "Redux",
                "RequireJS",
                "Rest",
                "Rich Faces",
                "Servlet  JSP",
                "SmartGWT",
                "SOA",
                "Socket.io",
                "Spring",
                "Spring Web Flow",
                "Struts",
                "Swagger",
                "SweetDev",
                "SWT",
                "Symfony",
                "Taglib5",
                "Tapestry",
                "Vue.js",
                "Web Services",
                "Webpack",
                "Zend Framework",
            ],
            "Workflow" => [
                "BPEL",
                "Domino Workflow",
                "W4",
            ]
        ];

        foreach ($data as $cat => $skills) {
            $cat = SkillsCategory::create([
                'title' => $cat
            ]);
            foreach ($skills as $skill) {
                Skill::create([
                    'category_id' => $cat->id,
                    'title' => $skill
                ]);
            }
        }

    }
}
